### ISSUE TITLE
Missing styles

### ISSUE THREAD

**Issue by Joel-Jensen** [vueup/vue-quill#11]
Hi! When I installed it (twice) via npm, according to the docs: `npm install @vueup/vue-quill@alpha --save` I was missing all the .css files. 

However when I installed it according to [npmjs.com](https://www.npmjs.com/package/@vueup/vue-quill) with `npm i @vueup/vue-quill` I got all the .css files.

No expert at all in npm so maybe something wrong with my setup but currently running a Laravel Sail environment with default settings in Laravel Mix.

**Comment by luthfimasruri** [comment]
Update to the latest alpha, it should be fine now:
`npm install @vueup/vue-quill@alpha --save` or `npm install @vueup/vue-quill@1.0.0-alpha.35 --save`
