### ISSUE TITLE
the 'modules' property of 'options' can't work when i use :options to config eidtor

### ISSUE THREAD

**Issue by a591537394** [vueup/vue-quill#115]
**Version**
@vueup/vue-quill version [^1.0.0-beta.7]

**Code**
NO.1
![image](https://user-images.githubusercontent.com/45918609/140875183-1051e024-8a51-4fd3-9200-1f9fb6b2eac7.png)
![image](https://user-images.githubusercontent.com/45918609/140875471-6916edd7-ea2f-4d6f-8bad-913691aed594.png)
![image](https://user-images.githubusercontent.com/45918609/140875294-e5a06094-c011-4fec-badf-7e70791decfd.png)

NO.2
![image](https://user-images.githubusercontent.com/45918609/140875928-e7c3737e-2912-4601-836f-cf30347b1134.png)
![image](https://user-images.githubusercontent.com/45918609/140875879-049d3d0f-008b-4ec9-b4c5-fc7680507bb2.png)
![image](https://user-images.githubusercontent.com/45918609/140875845-3bcd3986-b052-4389-afa8-96e5ce2a15ba.png)

**Describe the bug**
the config of the property 'modules' of 'options' prop of quill-editor component is not take effect.

**To Reproduce**
1. Config editor like the code case
2. Run application
3. Route to the page which had been configured the editor.
4. and then you will found the all config about modules is all not take effect

**Solve Method**
there is my currently way that used to avoid the bug
![image](https://user-images.githubusercontent.com/45918609/140877177-b6691c75-42e4-4e61-a624-5dc90eea6adc.png)
![image](https://user-images.githubusercontent.com/45918609/140877206-bdf74ca5-9610-4d00-91a7-53280b57b8a0.png)
![image](https://user-images.githubusercontent.com/45918609/140877271-8d593981-fcc3-4a4e-87fe-52fddd3386b9.png)

**Comment by gap1994** [comment]
`<QuillEditor
    ref="editor"
    v-model:content="content"
    contentType="html" 
    theme="snow"
    toolbar="full"
    :options="options"
  />`

`
const editor = ref(null)
const content = ref('<p>hello</p>')

// not work
const options = {
  modules: {
    clipboard: {
      matchers: [[Node.ELEMENT_NODE, handlecustommatcher]],
    }
  }
}

onMounted(() => {
// It work
  editor.value.getQuill().clipboard.addMatcher(Node.ELEMENT_NODE, handlecustommatcher)
})


`
So am I.
If you have resolution,remeber tell me.
