### ISSUE TITLE
Nuxt3 compatibility

### ISSUE THREAD

**Issue by PMLS3** [vueup/vue-quill#116]
**Version**
@vueup/vue-quill version ^1.0.0-beta.7
Nuxt 3
**Describe the bug**

ReferenceError: document is not defined in node_modules\quill\dist\quill.js

**To Reproduce**
1. Create nuxt3 App,
2. install @vueup/vue-quill
3. create plugins folder
4. create quill.ts file
5. Add: import { defineNuxtPlugin } from '#app'
import { QuillEditor } from '@vueup/vue-quill'
import '@vueup/vue-quill/dist/vue-quill.snow.css';
import '@vueup/vue-quill/dist/vue-quill.bubble.css';
export default defineNuxtPlugin(nuxtApp => {
  // Doing something with nuxtApp
  nuxtApp.vueApp.component('QuillEditor', QuillEditor);
})

**Browser (please complete the following information):**
 - Chrome

**Comment by PMLS3** [comment]
Sorry! It's working 100%... on nuxt3 you can make your plugins clientside by renaming your file quill.client.ts

**Comment by Robelk3005** [comment]
Hello @PMLS3  
Did the same as you but I'm getting this error --> 

```
Failed to resolve component: QuillEditor
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```
i added into component like this.
<div>
      <ClientOnly>
        <QuillEditor />
    </ClientOnly>
    </div>
    
   How did you resolved this? 
   Thanks for your help.

**Comment by andysay** [comment]
> Sorry! It's working 100%... on nuxt3 you can make your plugins clientside by renaming your file quill.client.ts

how import module to this plugin ?
