### ISSUE TITLE
Packaging error indicating missing declaration file

### ISSUE THREAD

**Issue by llyyayx** [vueup/vue-quill#117]

**Comment by llyyayx** [comment]
quill-delta
  -- lib
     --delta.d.ts （Please provide the）
     --op.d.ts  （Please provide the）

**Comment by llyyayx** [comment]
error TS7016: Could not find a declaration file for module '@vueup/vue-quill'. 'E:/talentBusiness/node_modules/@vueup/vue-quill/dist/vue-quill.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vueup__vue-quill` if it exists or add a new declaration (.d.ts) file containing `declare module '@vueup/vue-quill';`

38 import { QuillEditor } from '@vueup/vue-quill'
                               ~~~~~~~~~~~~~~~~~~

**Comment by wuliupo** [comment]
add a new file `src/quill.d.ts` as 
```ts
declare module '@vueup/vue-quill';
```

**Comment by zepingwong** [comment]
maybe u can try 
npm i quill-delta
