### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by EmreErinc** [vueup/vue-quill#12]
I download the library with npm and i got `"Object(...) is not a function"` error where implemented component. Also i got this error on main.js. Which point that i'm missing?

I'm following this [guideline](https://vueup.github.io/vue-quill/guide/installation.html)

Project using 
`"vue": "~2.6.11"`

Current vue-quill
`"@vueup/vue-quill": "^1.0.0-alpha.35"`

**Comment by luthfimasruri** [comment]
VueQuill didn't support Vue 2.x.x, it's only for Vue 3

**Comment by EmreErinc** [comment]
I missed that point, thanks.
