### ISSUE TITLE
How to insert the specified html content at the cursor position?

### ISSUE THREAD

**Issue by ZHT131** [vueup/vue-quill#123]
How to insert the specified html content at the cursor position?

**Comment by Grzyb9k** [comment]
I'm looking for a full day solution to the same problem but can't find anything in February  2022.

**Comment by hqy479992** [comment]
let quill = this.$refs.quillEditor.getQuill() //获取quillEditor实例
let pos = quill.selection.savedRange.index //获取光标位置
let insertStr = e.name  // 插入的内容
quill.insertEmbed(pos, insertStr); //在光标位置插入
quill.setSelection(pos + insertStr.length); //设置光标的位置 reset position
