### ISSUE TITLE
Cannot read properties of undefined (reading 'setHTML')

### ISSUE THREAD

**Issue by nerocil** [vueup/vue-quill#158]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.7]

```
const editor = ref()
...
<QuillEditor ref="editor" ... />
...
editor.value.setHTML(htmlContnet)
```
Throw error
 Cannot read properties of undefined (reading 'setHTML')

**Comment by nilarcs** [comment]
you cannot use setHTML method in setup, but can use in onMounted or later.
