### ISSUE TITLE
quill-blot-formatter bugs

### ISSUE THREAD

**Issue by whr2349** [vueup/vue-quill#186]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.8]

**Describe the bug**
When I install the plug-in “quill-blot-formatter ^1.0.5”, and it words in development env.
But , but it doesn't works in product env.
"Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'className')"
 the plug-in “quill-blot-formatter" has bug

**Comment by TheAustinG** [comment]
Trying importing from dist instead
`import BlotFormatter from 'quill-blot-formatter/dist/BlotFormatter`

**Comment by whr2349** [comment]
> 

好的，我试试，谢谢🙏
