### ISSUE TITLE
v-model:content not working when changed the binding value

### ISSUE THREAD

**Issue by erhuabushuo** [vueup/vue-quill#188]
v-model:content not working when changed the binding value, it seems not two way binding,

@feature

**Comment by aydot** [comment]
@erhuabushuo 
Did you try it like so:
```<QuillEditor  v-model:content="myContent"  contentType="html"/>```

**Comment by thedomeffm** [comment]
Solved this problem like this (vue 3 with TS):

```
<template>
    <div class="app-editor">
        <QuillEditor ref="editor"
                     :options="options"
                     content-type="html"
                     v-model:content="value" />
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { QuillEditor } from '@vueup/vue-quill';
import '@vueup/vue-quill/dist/vue-quill.snow.css';

export default defineComponent({
    name: 'AppHtmlEditor',

    components: {
        QuillEditor,
    },

    props: {
        modelValue: {
            type: String,
            required: false,
            default: null,
        },
    },

    emits: ['update:modelValue'],

    data() {
        return {
            // https://vueup.github.io/vue-quill/guide/options.html#option-attributes
            options: {
                // debug: 'info',
                toolbar: 'essential',
                placeholder: '...',
                theme: 'snow',
            },
        };
    },

    computed: {
        value: {
            get(): any {
                // check that the editor is mounted
                if (this.$refs.editor) {
                    this.$refs.editor.setHTML(this.modelValue);
                }
                return this.modelValue;
            },
            set(newValue: string | null) {
                this.copy = newValue;
                this.$emit('update:modelValue', newValue);
            },
        },
    },
});
</script>
```

**Comment by vz-spr** [comment]
Didn't work for me @thedomeffm , because cursor moved to the beginning for some reason.
The main problem was that when initialised quill receive `null` or `undefined`.
But then i needed to update after fetch this data from server.
So i found another robust solution which main idea is something like:

`
<script lang="ts" setup>
import Quill from 'quill'
import {onMounted, ref, watch} from 'vue'


const props = defineProps<{
    modelValue: string|null
    syncValue?: string|null
}>()
const emits = defineEmits(['update:modelValue'])
const div = ref(null)
let quill = null
onMounted(() => {
    quill = new Quill(div.value, {
        theme: 'snow'
    })

    quill.on('text-change', () => {
        console.log('--- text change', quill.root.innerHTML)
        emits('update:modelValue', quill.root.innerHTML)
    })
})
let _syncValue = props.syncValue
watch(props,  (newP) => {
    console.log('--- sync value, new and old', newP.syncValue, _syncValue)
    if (newP.syncValue === _syncValue) {
        return
    }
    let delta = quill.clipboard.convert(newP.syncValue)
    quill.setContents(delta, 'api')
    _syncValue = newP.syncValue
})
</script>

<template>
    <div class="quill-wrapper" ref="div"></div>
</template>
`

**Comment by carlos-mora** [comment]
This one is a significant issue, as it's spected to work as usual with v-models. 
Changing underlying data is a regular practice. Please pay attention to this.

**Comment by thedomeffm** [comment]
As can be seen with Issue https://github.com/vueup/vue-quill/issues/275, people still don't understand the behaviour of the editor!
As a solution one should either explain the behaviour in the documentation or solve the reactivity in vue-quill!

**Comment by Tofandel** [comment]
It's so trivial to fix the reactivity with an intermediate variable, I can make a PR

**Comment by cmora-pe** [comment]
Please!!!

**Comment by PDSAPWCV** [comment]
As common practice, changes on v-model are not reflected in the editor.

You can fix this problem by calling quilljs's internal API directly. (Use refs)
[https://quilljs.com/docs/api/#setcontents](https://quilljs.com/docs/api/#setcontents)

This solution is based on the assumption that contents are provided via props.

```vue
<template>
      <QuillEditor ref="quill" theme="snow" toolbar="essential" v-model:content="data.contents" content-type="delta"/>
</template>

<script>
import { QuillEditor } from '@vueup/vue-quill'
import '@vueup/vue-quill/dist/vue-quill.snow.css'

export default {
  name: 'editor-component',
  components: { QuillEditor },
  props: {
    data: {
      type: Object,
      default: null,
    },
  },
  data() {
    return {
      data: {
        id: null,
        contents: '',
      },
    }
  },
  watch: {
    data: {
      deep: true,
      handler(newData, prevData) {
        this.data = {
          id: newData.id,
          // contents: JSON.parse(newData.contents),
        }
        this.updateEditor(JSON.parse(newData.contents)) // delta json string from server
      },
    },
  },
  computed: {
  },
  methods: {
    updateEditor(delta) {
      this.$refs.quill.setContents(delta)
    },
  },
}
</script>

<style scoped lang="less">
</style>
```

**Comment by Tofandel** [comment]
> As common practice, changes on v-model are not reflected in the editor.

Not common and not intended, the common behavior of a v-model is to have 2 way binding, using refs is just a hack

I made the PR to fix the bug already, it works very well, I need to test it with deltas still when I got time

**Comment by nathanchase** [comment]
There's still seemingly no way to wrap `<QuillEditor>` inside of your own custom component. I want to do something like the following, where you set a v-model on your custom component, and it bubbles up from QuillEditor when its value changes:

```ts
// RichTextEditor.vue
<template>
  <ClientOnly>
    <QuillEditor
      class="editor"
      :placeholder="placeholder"
      theme="bubble"
      :value="modelValue"
      @input="$emit('update:modelValue', $event.target.value)"
    />
  </ClientOnly>
</template>

<script setup lang="ts">
import '@vueup/vue-quill/dist/vue-quill.bubble.css';

defineProps({
  modelValue: {
    type: String,
    default: '',
    required: true,
  },

  placeholder: {
    type: String,
    default: '',
    required: false,
  },
});

defineEmits(['update:modelValue']);

if (!process.server) {
  const { QuillEditor } = await import('@vueup/vue-quill');
  const { vueApp } = useNuxtApp();
  if (!vueApp._context.components.QuillEditor) {
    vueApp.component('QuillEditor', QuillEditor);
  }
}
</script>
```
```ts
// OtherComponent.vue
<RichTextEditor v-model="myvalue" />
```

**Comment by Tofandel** [comment]
There is no reason you need to introduce an intermediate reactive variable, that's a lot of redundant code

`@update:content` is called when your content update so there is no need to introduce `v-model` in a wrapped component or you'll be causing double updates

```vue
<template>
  <div>
    <div class="editor">
      <QuillEditor
        :content="props.modelValue"
        content-type="html"
        :options="defaultOptions"
        :placeholder="placeholder"
        theme="bubble"
        @update:content="handleChange"
      />
    </div>
  </div>
</template>
      
<script setup lang="ts">
import '@vueup/vue-quill/dist/vue-quill.bubble.css';
import 'quill-paste-smart';

const props = defineProps({
  modelValue: {
    type: String,
    default: '',
    required: false,
  },

  placeholder: {
    type: String,
    default: '',
    required: false,
  },
});

const emit = defineEmits(['update:modelValue']);

const defaultOptions = ref({
  theme: 'bubble',
  modules: {
    clipboard: {
      allowed: {
        tags: ['em', 'strong', 's', 'p', 'br', 'ul', 'ol', 'li', 'span'],
      },
      keepSelection: true,
    },
    toolbar: [
      ['bold', 'italic', 'strike'],
      ['blockquote'],
      [{ list: 'ordered' }, { list: 'bullet' }],
      ['clean'],
    ],
  },
});

if (!process.server) {
  const { QuillEditor } = await import('@vueup/vue-quill');
  const { vueApp } = useNuxtApp();
  if (!vueApp._context.components.QuillEditor) {
    vueApp.component('QuillEditor', QuillEditor);
  }
}

const handleChange = (value: any) => {
  emit('update:modelValue', value);
};
</script>
```

**Comment by nathanchase** [comment]
@Tofandel Ok, this works and allows me to remove the computed property:
```ts
<QuillEditor
        :content="modelValue" // <- not 'props.modelValue', but just 'modelValue'
        content-type="html" // <- this HAS to be html... if it's not, it throws a recursion error
        :options="defaultOptions"
        :placeholder="placeholder"
        theme="bubble"
        @update:content="handleChange"
/>
```
Thanks for the help!

**Comment by lucas-fsousa** [comment]
Ideally, the v-model would work like any other form of input, since updates are constant when updating the textbox contents. I've tried all the ways above and it doesn't work for me, since I need to modify a lot of my code to do something that the template itself should provide, it's not something very interesting to use

**Comment by cortnum** [comment]
@Tofandel thank you my brother!! I was about to abandon this component because the two-way binding was broken.

**Comment by adrianhand** [comment]
Would thank anyone for a little help here as I try to get two-way binding working with vue-quill. I understand from the docs that v-model:content is the prop I need to use for two way binding. Here is my vue3 composition template in its simplest form:

```
<template>
    <quill-editor theme="snow" toolbar="full" v-model:content="selectedNote" content-type="delta" />
</template>

<script>
import { ref } from 'vue'

import { Delta, QuillEditor } from '@vueup/vue-quill'
import '@vueup/vue-quill/dist/vue-quill.snow.css'

export default {
    components: {
        QuillEditor,
    },
    setup() {
        let selectedNote = ref(new Delta())
        return { selectedNote }
    },
}
</script>
```

So my intent is to bind the editor contents 2-way with _selectedNote_ - the above appears to work but generates the following error in console "[Vue warn]: Maximum recursive updates exceeded."

However - everything works as expected if I change my content-type to text or html. Is there a way to have error-free two-way binding whilst also using delta as my content type?

**Comment by Tofandel** [comment]
Does the error still happens if you use `ref(new Delta([]);` ?

**Comment by adrianhand** [comment]
Good shout mate worth a try - have just done so though and the behaviour is the same. Have also noticed that every keypress moves the cursor back to the start of the editor window again.

Its not the end of the world if I have to use HTML, it just feels like using delta is a lot more elegant.

**Comment by adrianhand** [comment]
Okay Todandel, thank you again - have just tried that, I took a snippet from the demo folder on the repo, so the delta I made looks like this:

```
new Delta([{ insert: 'Gandalf', attributes: { bold: true } }, { insert: ' the ' }, { insert: 'Grey', attributes: { color: '#ccc' } }])
```

And the result was the same - but it brought me to trying to run the demos from the repo - and indeed when I do that, they produce the same error result; they too are two-way binding a delta object with v-model:content. I checked a different browser just to be sure and the behaviour was the same on Chrome and on Safari.

**Comment by Tofandel** [comment]
I've found the issue, it was a very small one, I'll make a follow up pr

**Comment by adrianhand** [comment]
Woo that’s mega, thank you Tofandel, giving your change a try 🙏

**Comment by Tofandel** [comment]
@adrianhand Are you sure you're on the correct branch if you pulled the fork? Because the pen is exactly as in the demo, which works fine

**Comment by adrianhand** [comment]
Ahhhhh mate I am so so sorry, when I pulled I assumed I would default to tofandel/master - I am sure switching to the right branch will do the trick, I am ashamed. Will follow up with a result.

**Comment by adrianhand** [comment]
Okay bud, you were absolutely right - sorry again(!) - I was not using your master branch. When checkout correctly everything works as expected with error-free two-way binding between v-model:content and my objects.

However (!) whilst every text change is reflected in my object, some operations like setting text style aren't pushed through to the model object. If I subsequently make a text change, reactivity forces the binding to refresh and my text styles are there in the delta.

Its a really little thing and I don't know what I can reasonably expect here.

**Comment by Tofandel** [comment]
Indeed, gave it a try and also pushed a fix for that as well

**Comment by umneeq2** [comment]
Why use such a plugin that complicates the work? He just needs to link v-model and that's it.

**Comment by cortnum** [comment]
This still doesn't work as it should.

I have a case, where I have multiple text editors spawned in a for loop. And when I insert one in the middle with an empty model value (''), and the component which renders the editor updates, the texteditor still has the text from the previous model value inside. If I insert one in the middle, which HAS a model value (eg. '.'), it works as expected.

It seems there is a problem when the model value was set to an empty string, that doesn't update the text you see on the screen. But the content value of the editor updates just fine.

**Comment by Tofandel** [comment]
@cortnum Are you using 1.1.0?

**Comment by cortnum** [comment]
@Tofandel yes I am. I will try to make one later today

**Comment by qiyongjin** [comment]
`<script setup name="QuillEditor">
  import { defineProps, ref, watch, reactive, onMounted, toRaw } from 'vue';
  import { QuillEditor, Quill } from "@vueup/vue-quill";
  import BlotFormatter from "quill-blot-formatter";
  import "@vueup/vue-quill/dist/vue-quill.snow.css";

  if (!Quill.imports["modules/BlotFormatter"]) {
    Quill.register("modules/BlotFormatter", BlotFormatter);
  }

  const props = defineProps({
    textContent: {
      type: String,
      default: '',
    }
  });

  // 定义content为响应式对象
  const contents = ref(`
  打上来看看
  <h2>还是十六客服的</h2>
  <p>杀骷髅反对吧打死了几分</p>
  <p>杀骷髅反对吧打死了几分</p>
`);

  const toolbar = ref([
    [{ size: ["small", false, "large", "huge"] }],
    [{ header: [1, 2, 3, 4, 5, 6, false] }],
    ["bold", "italic", "underline", "strike"],
    [{ color: [] }, { background: [] }],
    ["clean"],
    ["image"],
    ["link"],
    ["video"],
  ]);
watch(() => props.textContent, (newVal) => {
  contents.value = newVal;
}, {
  immediate: true
});
const options = reactive({
  modules: {
    BlotFormatter,
    toolbar: toolbar.value
  },
  placeholder: '請輸入內容...',
  theme: 'snow',
  theme:"bubble",
  default:contents.value,
  contentType: "delta" | "html" | "text",
  enable: true,
  readOnly: false,
});

  const myQuillEditor = ref(null)

  </script>

<template>
  <QuillEditor ref="myQuillEditor"
  v-model:content="contents"
  :options="options"/>
</template>`   The data cannot be rendered, and when the component passes in the data, it seems to have been rendered to the editor, but the editor automatically replaces all of them with empty labels

**Comment by Tofandel** [comment]
> contentType: "delta" | "html" | "text",

You need to choose one type, you can't pass multiple like this
