### ISSUE TITLE
v-model:content not update when i am fetching data from api

### ISSUE THREAD

**Issue by mahmudgitdev** [vueup/vue-quill#189]
this is my component

QuillEditor v-model:content="contents" :options="options" contentType="html

and here i am updating the contents value but it's not work
    mounted(){
      this.emitter.on("setDraftStory", (draft) => {
      this.contents = draft.story;
    });
    }

please help with that

**Comment by thedomeffm** [comment]
Make a ref on your quill editor and call the setHTML method:

```
<template>
        <QuillEditor ref="editor"
                     :options="options"
                     content-type="html"
                     v-model:content="value" />
</template>

// and 

this.$refs.editor.setHTML(this.modelValue);
```

**Comment by march1993** [comment]
> Make a ref on your quill editor and call the setHTML method:
> 
> ```
> <template>
>         <QuillEditor ref="editor"
>                      :options="options"
>                      content-type="html"
>                      v-model:content="value" />
> </template>
> 
> // and 
> 
> mounted(){
>   this.emitter.on("setDraftStory", (draft) => {
>     this.$refs.editor.setHTML(draft.story);
>   });
> }
> ```

Why is that? `v-model:content' is meant to be bi-directional binding I guess.

**Comment by zwoefler** [comment]
How would you do this with the "composition API"?
When I do: 
```
<template>
        <QuillEditor
          ref="editor"
          v-model:content="blogContent"
        />
</template>

//

<script>
    const editor = ref(null)

    editor.value.setHTML(article.content)
</script>
```

The Editor only shows:
```
[object Object]
```

**Comment by zwoefler** [comment]
> How would you do this with the "composition API"? When I do:
> 
> ```
> <template>
>         <QuillEditor
>           ref="editor"
>           v-model:content="blogContent"
>         />
> </template>
> 
> //
> 
> <script>
>     const editor = ref(null)
> 
>     editor.value.setHTML(article.content)
> </script>
> ```
> 
> The Editor only shows:
> 
> ```
> [object Object]
> ```

I was using the Quill-Delta instead of HTML. So according to the [documentation](https://vueup.github.io/vue-quill/api/methods.html#setcontents-content-source) you have to use the `setContents`-API.

Instead of: `editor.setHTML(article.content)` I used
`editor.value.setContents(article.content, 'api')`
