### ISSUE TITLE
I got error Cannot convert undefined or null to object adding QuillBetterTable into QuillEditor

### ISSUE THREAD

**Issue by sergeynilov** [vueup/vue-quill#190]
In laravel 9 with Inertiajs/vuejs 3 I need to add table into vueup/vue-quill editor
and looking at this article
https://vueup.github.io/vue-quill/guide/modules.html#example

Adding QuillBetterTable support into my app:

    <quill-editor
        :options="editorOptions"
        :modules="modules"
        theme="snow"
        :disabled="false"
        v-model:content="descriptionFormEditor.description"
        text-change="textChangeDescription"
        editorChange="editorChangeDescription"
        contentType="html"
        @blur="onEditorBlur($event)"
        @focus="onEditorFocus($event)"
        @ready="onEditorReady($event)"
        @textChange="onTextChange($event)"
    
    >{{ descriptionFormEditor.description }}
    </quill-editor>
    
        ...
        import { QuillEditor } from '@vueup/vue-quill'
        import '@vueup/vue-quill/dist/vue-quill.snow.css';
        import QuillBetterTable from 'quill-better-table' // https://github.com/soccerloway/quill-better-table
        ...
    
            let editorOptions = ref(
                [['better-table', 'bold', 'italic'], ['link', 'image']]
            )
    
            let modules = ref({
                    table: false,  // disable table module
                    'better-table': {
                        operationMenu: {
                            items: {
                                unmergeCells: {
                                    text: 'Another unmerge cells name'
                                }
                            },
                            color: {
                                colors: ['#fff', 'red', 'rgb(0, 0, 0)'],  // colors in operationMenu
                                text: 'Background Colors'  // subtitle
                            }
                        }
                    },
                    keyboard: {
                        bindings: QuillBetterTable.keyboardBindings
                    }
                }
            )
    	...
    	
    	...
     return      
         editorOptions,
         modules,
    
    	...

But I got next error : https://prnt.sc/EIKGal7poJyT

        "@vueup/vue-quill": "^1.0.0-beta.8",
        "vue": "^3.2.30",
        "vue-loader": "^16.1.2"

Any hints what is it and how it can be fixed ?

Thanks!

**Comment by arnosolo** [comment]
I'm trying to add table support in @vueup/vue-quill. Do you know how to do this? Can you show me an example? Thank.

**Comment by FreakYGG** [comment]
@arnosolo , Hi there, did you by any chance get an example somewhere for table support within vue-quill?

I am struggling to get something working. Unless you went with another quill editor for vue3

**Comment by ycldz** [comment]
> @vueup/vue-quill'e tablo desteği eklemeye çalışıyorum. Bunu nasıl yapacağımı biliyor musunuz? Bana bir örnek gösterebilir misiniz? Teşekkürler.

+1
