### ISSUE TITLE
I can`t set full html content with css

### ISSUE THREAD

**Issue by Grzyb9k** [vueup/vue-quill#193]
@vueup/vue-quill 1.0.0-beta.8
@vue 3.2.29

I want to edit in textarea field(with QuillEditor)  content from API which i get in HTML format with CSS classes. 
I tried many solutions which i found on the internet. But no one works good.

I set in template:
```
<QuillEditor
                   ref="mainContent"
                   v-model:content="form.content"
                   style="min-height: 300px"
                   :options="editorOptions"
                   theme="snow"
                   content-type="html"
                                />
```

When i use:
```
this.$refs.mainContent.setHTML("<div class="test">lol</div>");
```
I have error `Uncaught TypeError: this.emitter is undefined` and field are empty.

but when i use:
```
this.$refs.mainContent.pasteHTML("<div class="test">lol</div>");
```
I get field content in html but css classes are striped and `<div>` was swapped to `<p>`.

Can someone help me and tell what I need to do?

**Comment by TylerMRoderick** [comment]
I believe this issue has to do with the way Quill handles pasted html. Not specific to this Vue wrapper library.

With that said, one workaround is to set your editor's default block type to 'DIV' before using `setHTML`.

```javascript
const Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);

this.$refs.mainContent.setHTML("<div class="test">lol</div>");
```

If more configuration is needed, the Quill clipboard module is where I would start digging https://quilljs.com/docs/modules/clipboard
