### ISSUE TITLE
Missing ref owner context. ref cannot be used on hoisted vnodes.

### ISSUE THREAD

**Issue by ccwebgroup** [vueup/vue-quill#218]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.8]

[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

[Vue warn]: onBeforeUnmount is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function

**Comment by Julian367** [comment]
Hello, how did you solve this problem?

**Comment by ccwebgroup** [comment]
I have set it up correctly
```
import { QuillEditor } from "@vueup/vue-quill";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
import "@vueup/vue-quill/dist/vue-quill.bubble.css";

app.component("QuillEditor", QuillEditor);
```
Component
```
 <QuillEditor
      v-model:content="blogForm.body"
      contentType="html"
      theme="bubble"
      :toolbar="toolbar"
      :modules="modules"
      @ready="quillReady"
    />
```
