### ISSUE TITLE
quill overwriting modules

### ISSUE THREAD

**Issue by ccwebgroup** [vueup/vue-quill#226]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.5]

quill Overwriting modules/blotFormatter with ƒ BlotFormatter2(quill) {
        var _this = this;
        var options = arguments.length > 1 && arguments[1] !== void 0 ? arguments[1] : {};
        _classCallCheck(this, BlotFormatter2);

**Comment by jdinartejesus** [comment]
Can we open this issue? @ccwebgroup @luthfimasruri  because still happens when you've multiple quill editors on the same page with modules.
