### ISSUE TITLE
Some Question about Quill-better-table

### ISSUE THREAD

**Issue by paker-zhang** [vueup/vue-quill#227]
Hi, @luthfimasruri 

I found Table Module on [document](https://vueup.github.io/vue-quill/guide/modules.html#quill-modules), But `quill-better-table` and `quill-table-ui` Requirements is `quilljsv2.0.0-dev.3` .

And I checked vue-quill is base on quill v1.3.7.
If I want to use table module, what should I do? can I update Quill or install and use directly?

Thanks.

**Comment by arnosolo** [comment]
I'm trying to add table support in @vueup/vue-quill. Do you know how to do this? Can you show me an example? Thank.

**Comment by paker-zhang** [comment]
> I'm trying to add table support in @vueup/vue-quill. Do you know how to do this? Can you show me an example? Thank.

I don't have another solution, at last I try to create a table module without `@vueup/vue-quill` in my business project.
The business project is finish, so I didn't permission to show you any example, but I can tell is build on `Document API`.

Wish you can get any help in here.

**Comment by ycldz** [comment]
+1
