### ISSUE TITLE
Editor always grabs focus when mounted

### ISSUE THREAD

**Issue by dwheeldo** [vueup/vue-quill#25]
When the component mounts, it automatically grabs focus. This isn't desirable behaviour when the editor is rendered in a form with other components.

(Fantastic component by the way!)

**Comment by luthfimasruri** [comment]
which version did you use, and can you share the source code?

**Comment by dwheeldo** [comment]
Hi,

The version in my `package.json` is `^1.0.0-beta.3`.

The source code is pretty basic - just using v-model and firing a save event on blur:

```
<QuillEditor
   v-model:content="inputValue"
   content-type="html"
   :options="options"
   theme="snow"
   @blur="saveResponse"
/>
```
