### ISSUE TITLE
Issue with quill-blot-formatter

### ISSUE THREAD

**Issue by Nelwhix** [vueup/vue-quill#250]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.5]

I used quill-blot-formatter and it resulted in a vite build error. So I found another package, xeger/quill-image and had this issue https://github.com/xeger/quill-image/issues/14. The solution makes the other buttons in the toolbar misbehave. Is there a way you can tell me what to do differently

1. Install  xeger/quill-image via npm
2. Register it the way you would register quill-blot-formatter
3. when you try to use it you will get this error https://github.com/xeger/quill-image/issues/14

**Comment by aeon3k** [comment]
did you find a way ? @Nelwhix
