### ISSUE TITLE
alpha version lib has bug

### ISSUE THREAD

**Issue by asasugar** [vueup/vue-quill#260]
**Version**
@vueup/vue-quill 1.0.0-alpha.1

**Describe the bug**

1. QuillEditor ts declare non-existent
2. The reporting component does not exist, and the style does not exist

**Browser (please complete the following information):**
 - Browser [chrome]
 - Version [97.0.4692.99]

**Additional context**

```vue
<template>
  <quill-editor
    v-model:content="richContent"
    content-type="html"
    theme="snow"
    toolbar="full"
    placeholder="请输入..."
    v-bind="{ ...attrs }" />
  <el-divider content-position="left">Render Html</el-divider>
  <el-input
    v-model="richContent"
    :rows="10"
    :autosize="{ minRows: 10, maxRows: 10 }"
    type="textarea"
    :readonly="true"
    placeholder="html" />
</template>
<script lang="ts" setup>
import { QuillEditor } from '@vueup/vue-quill';
import '@vueup/vue-quill/dist/vue-quill.snow.css'
import { ref, useAttrs } from 'vue';

const richContent = ref('');
const attrs = useAttrs();
</script>

```

**Comment by asasugar** [comment]
@vueup/vue-quill 1.0.0-beta.10 is work good

**Comment by Tofandel** [comment]
Then use `@vueup/vue-quill 1.0.0-beta.11` and you can close this issue 😅 

Alpha.1 is the oldest release it's been superseeded by more than 50 versions, so opening issues about old releases is unnecessary
