### ISSUE TITLE
Error: Can't resolve 'vue'

### ISSUE THREAD

**Issue by ivanasetiawan** [vueup/vue-quill#27]
**Describe the bug**

**To Reproduce**
1. Install using `npm install @vueup/vue-quill@beta --save`
2. Import using `import { QuillEditor } from '@vueup/vue-quill';`
3. See error on Terminal

**ERR message**
ERROR in ./node_modules/@vueup/vue-quill/dist/vue-quill.esm-bundler.js
Module not found: Error: Can't resolve 'vue' in '/Users/myusername/Sites/projectname/node_modules/@vueup/vue-quill/dist'
 @ ./node_modules/@vueup/vue-quill/dist/vue-quill.esm-bundler.js 15:0-91 48:20-35 117:8-17 120:8-23 125:23-26 212:30-33 218:8-13 292:12-20 299:8-13 304:8-13 326:12-13
 @ ./static/js/vue/blog/App.js

**Expected behavior**
As seen on https://vueup.github.io/vue-quill/guide/usage.html

**Comment by luthfimasruri** [comment]
have you installed `vue`?

**Comment by ivanasetiawan** [comment]
@luthfimasruri  yep! my project is using `Vue 3.0.2` (NPM version, not vue-cli)
This is what I did:

`
import { createApp, defineAsyncComponent, onMounted } from 'vue/dist/vue.esm-browser.js';
import { QuillEditor } from '@vueup/vue-quill';

const blog = createApp({
  delimiters: ['[[', ']]'],
  components: {
    QuillEditor
  },
  setup() {
    return {}
  },
});

blog.mount('#blog-app');
`

and on my terminal I ran `npx webpack --watch` and got the ERR
