### ISSUE TITLE
Quill editor can't recognize outside changes

### ISSUE THREAD

**Issue by turanibrahim** [vueup/vue-quill#275]
Hi everyone, I want to change content inside quill editor programmatically. When I update `content` prop on parent component, quill editor component `content` prop updates, but content inside the editor stays the same. I think this issue related to commented code below. Why this code block commented? Did that on purpose, or it's just a mistake?

https://github.com/vueup/vue-quill/blob/b35c17302567433666e1fc076e849de426dd1381/packages/vue-quill/src/components/QuillEditor.ts#L309

**Comment by turanibrahim** [comment]
I think you did that on purpose, otherwise cursor moving to start of the editor every time when user but space or copty something, but I think we should find a way to fix this because I need to re-render the component every time the content changes by parent component

**Comment by turanibrahim** [comment]
Duplicate issue #188

**Comment by mohammedmoutawakkil** [comment]
> I think you did that on purpose, otherwise cursor moving to start of the editor every time when user put space or copy something, but I think we should find a way to fix this because I need to re-render the component every time the content changes by parent component

I have the same problem
