### ISSUE TITLE
Vue Quill is logging messages in the console

### ISSUE THREAD

**Issue by greekFreakDinos90** [vueup/vue-quill#278]
**Version**
"@vueup/vue-quill": "^1.0.0",

**Describe the bug**
Messages are being logged in the browser console by VueQuill.

![image](https://user-images.githubusercontent.com/117083425/200612207-ff38f69b-0ff4-4afb-9f56-fd43d490fffe.png)

**To Reproduce**
1. Insert <QuillEditor /> component in a template of a vue signle file component.
2. When the respective component is rendered the message appears in the console.

**Expected behavior**
No messages should be logged in the console.

**Browser (please complete the following information):**
 - Chrome
 - Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by Tofandel** [comment]
It doesn't for me, you may just have activated the debug module (or one of your added modules did) which is globaly activated https://quilljs.com/docs/api/#debug

**Comment by makerovski** [comment]
Hello,

It does the same for me, I am using in a nuxt app ... is there a solution ?
