### ISSUE TITLE
Vite Inertai Js and Laravel, shows Super expressions error

### ISSUE THREAD

**Issue by OGhawsi** [vueup/vue-quill#289]
**Version**
@vueup/vue-quill version 1.0.0

**Describe the bug**
I have installed Laravel 9 along with inertia and vue3, when I run **npm run dev** in my development environment everything works fine, the problem comes whenever I build my project for production through **npm run build** all the assets are compiled successfully and no error is shown. When I push the code to production and try to open any page that has imported vue-quill throws the following error in the console:
_Uncaught (in promise) TypeError: Super expression must either be null or a function, not undefined_

**Additional context**
I have also removed and reinstalled vue-quill and also rebuilt the project many times but I don't know where the problem is.

Without vue-quill everything runs smoothly.

**Comment by jlecointecaplaser** [comment]
Same error with:

Node: 18.7..0
Npm: 8.15.0
Vite: 4.0.1
Vue:3.2.45
On Debian

```
<template>
  <div>
    <QuillEditor
      ref="quillContent"
      :content="props.content"
      :modules="quillModules"
      :toolbar="quillToolbar"
      :options="{ debug: 'none', placeholder: props.placeholder }"
      theme="snow"
      contentType="html"
      @update:content="(content) => emit('change', content)"
      :style="'min-height: '+height+'px;'"
    />
  </div>
</template>
<script setup>
import { QuillEditor } from '@vueup/vue-quill'
import BlotFormatter from 'quill-blot-formatter' // permet de redimensionner les images
import ImageCompress from 'quill-image-compress' // drag & drop image + compression
import '@vueup/vue-quill/dist/vue-quill.snow.css'

const props = defineProps({
  content: {
    type: String,
    default: ''
  },
  disabled: {
    type: Boolean,
    default: false
  },
  height: {
    type: Number,
    default: 300
  },
  placeholder: {
    type: String,
    default: ''
  }
})
const quillContent = ref()

const emit = defineEmits(['change'])

const quillModules = [
  {
    name: 'blotFormatter',
    module: BlotFormatter
  },
  {
    name: 'ImageCompress',
    module: ImageCompress,
    options: {
      quality: 0.7,
      maxWidth: 800,
      maxHeight: 800,
      imageType: 'image/jpeg',
      debug: false, // affiche messages dans la console lors de l'ajout d'une image
      suppressErrorLogging: true
    }
  }
]

const quillToolbar = [
  [{ header: 1 }, { header: 2 }],
  ['bold', 'italic', 'underline', 'strike'],
  ['blockquote', 'code-block'],
  [{ list: 'ordered' }, { list: 'bullet' }],
  [{ script: 'sub' }, { script: 'super' }],
  [{ indent: '-1' }, { indent: '+1' }],
  [{ color: [] }, { background: [] }],
  [{ align: [] }],
  ['link', 'image', 'video'],
  ['clean']
]
</script>

<style scoped>
.ql-snow .ql-picker {
  height: initial!important;
}
</style>
```

**Comment by Stoner609** [comment]
BlotFormatter is problem.

**Comment by mariusberget92** [comment]
Same problem. BlotFormatter is indeed the problem.

**Comment by anburocky3** [comment]
Any update on this?

**Comment by mariusberget92** [comment]
Still facing this issue. It does for some reason work in a development environment (`npm run dev`). After build (`npm run build`) the error comes back.

**Comment by zxy-Jackie** [comment]
Has anyone solved this problem yet?

**Comment by mariusberget92** [comment]
Haven't even bothered trying to fix a project that seems to abandoned. Its the BlotFotmatter plugin or module that's makes it break.

**Comment by rits423** [comment]
is still here...

**Comment by rits423** [comment]
https://github.com/Fandom-OSS/quill-blot-formatter/issues/39

maybe can help someone
