### ISSUE TITLE
Setting matchVisual on clipboard module

### ISSUE THREAD

**Issue by ntoljic** [vueup/vue-quill#29]
**Describe the bug**
When pasting formatted content into the editor, sometimes additional line breaks are inserted.
While pasting is a pain in quill in general, I believe that this particular issue has been addressed (https://github.com/quilljs/quill/issues/1483).
My problem is that I cannot seem to configure the clipboard module correctly to set `matchVisual` to `false`.

**To Reproduce**
1. Go to https://vueup.github.io/vue-quill/
2. Remove the text in the editor and insert one line without formatting and another line as e.g. a blockquote
3. Cut and paste the entire content within the same editor
4. An extra line break is inserted between the two lines

**Expected behavior**
Only the previously cut (or copied) text should be pasted, nothing more.

**Additional context**
I have tried setting `quill.clipboard.options.matchVisual = false;` within `onMounted` of my component but that didn't help.

Any help would be highly appreciated.

**Comment by luthfimasruri** [comment]
This is a quill issue.
In my case, it only happens in Firefox (tested in chrome, firefox, brave, & edge).
you can use addMatcher to solve this:
``` js
const onReady = (quill) => {
quill.clipboard.addMatcher("p", (node, delta) => {
const op = delta.ops[0];
op.insert = op.insert.replace("\n\n", "\n");
return delta;
});
};
```
[Source code link](https://codesandbox.io/s/extra-space-when-pasting-rxtzq?file=/src/components/MyEditor.vue)
but I'm not sure if it fixes your problem or not.

**Comment by ntoljic** [comment]
Thanks for the snippet and sorry for the delayed reply. Unfortunately, your suggestion did not fix my problem. But since I have a few other issues with quill, I am not sure when I will have the chance to revisit this.
