### ISSUE TITLE
Warning printed: Added synchronous DOM mutation listener to a 'DOMNodeInserted' event.

### ISSUE THREAD

**Issue by xiki808** [vueup/vue-quill#290]
When using <QuillEditor /> a warning is generated for each element used in the console:

`Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.`

**Comment by carlos-mora** [comment]
I'm having the same issue, not sure if I should post it again or keep this alive.
May be there is something related to compatibilityMode on Quill options.
