### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by DomasB** [vueup/vue-quill#294]
**Version**
@vueup/vue-quill version 1.0.0

**Describe the bug**
Syntax highlighting does not work. Text is not recognized as code and not separated with additional tags.
While debugging I can see that Syntax internal module is being registered but highlight method remains null (is not taken from options).

**To Reproduce**
```vue
<template>
  <QuillEditor
    v-model:content="value"
    :toolbar="toolbar"
    :options="options"
    :modules="modules"
    content-type="html"
    theme="bubble"
  />
</template>

<script>
import { QuillEditor } from "@vueup/vue-quill";

import hljs from "highlight.js";
import "highlight.js/styles/github.css";

hljs.configure({
  languages: ["javascript"],
});

export default {
  components: {
    QuillEditor,
  },
  data() {
    return {
      value: "function test() { console.log('TEST') }",
      options: {
        modules: {
          syntax: {
            highlight: (text) => hljs.highlightAuto(text).value,
          },
        },
      },
      toolbar: [[{ header: 1 }], ["code-block"]],
    };
  },
};
</script>
```

**Expected behavior**
Syntax highlighting working if set up according to documentation.

**Reproduction link**
https://codesandbox.io/embed/compassionate-noyce-go92rl?fontsize=14&hidenavigation=1&theme=dark

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 108.0.5359.95

**Comment by Nelwhix** [comment]
Hello @DomasB  can you check the codesandbox. I am getting TypeError: Failed to Fetch

**Comment by DomasB** [comment]
The issue is still relevant and affecting our use of the library.
