### ISSUE TITLE
it doesn't work!

### ISSUE THREAD

**Issue by jerryyan1990** [vueup/vue-quill#31]
**Version**
 "@vueup/vue-quill": "^1.0.0-alpha.1",

**Describe the bug**
install and follow the document to use,it's just can't work!

my whole code：

![微信截图_20210525114400](https://user-images.githubusercontent.com/12929365/119436315-86b46480-bd4e-11eb-8b99-2bee5dd1ef13.png)

chrome console：
![微信截图_20210525113601](https://user-images.githubusercontent.com/12929365/119436158-3fc66f00-bd4e-11eb-8043-1e28b7698561.png)

**Comment by luthfimasruri** [comment]
Make sure to use the latest version 

``` js
npm install @vueup/vue-quill@beta --save
# OR
yarn add @vueup/vue-quill@beta
```

**Comment by luthfimasruri** [comment]
Docs: `https://vueup.github.io/vue-quill/guide/installation.html#cdn`

**Comment by jerryyan1990** [comment]
> Make sure to use the latest version
> 
> ```js
> npm install @vueup/vue-quill@beta --save
> # OR
> yarn add @vueup/vue-quill@beta
> ```
> 
> OR
> 
> ```js
> npm install @vueup/vue-quill@1.0.0-beta.5 --save
> # OR
> yarn add @vueup/vue-quill@1.0.0-beta.5
> ```
install with @beta is working! thank u a lot!

the document install use @latest, please update document!
