### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'emit') - when using contentType="html"

### ISSUE THREAD

**Issue by eigriffiths** [vueup/vue-quill#310]
### Discussed in https://github.com/vueup/vue-quill/discussions/309

<div type='discussions-op-text'>

<sup>Originally posted by **eigriffiths** January 18, 2023</sup>
Hi guys, really enjoying using VueQuill however i am having an issue when rendering a html string in the editor. 

I receive the following console error when using contentType="html"

![KGQqD](https://user-images.githubusercontent.com/22006555/213208086-4eae9ee0-6f18-4534-a034-488c484b7eb5.png)
 
The following code returns this error - 

```
<template>
  <div class="">
      <QuillEditor v-model:content="data" contentType="html" />
  </div>
</template>

<script>
import { QuillEditor } from '@vueup/vue-quill'
import '@vueup/vue-quill/dist/vue-quill.snow.css';

export default {
  name: 'HomeView',
  components: {
    QuillEditor
  },
  setup(){
    const data = "<div><p>test test test</p></div>"

    return {
      data
    }
  }
}
</script>
```

This error only appears when using the following prop contentType="html" The error does not show when using contentType="text".

I have tried the following to ensure that the data is mounted before creating QuillEditor however this does not work.

```
<div v-if="data !== undefined">
  <QuillEditor v-model:content="data" contentType="html" />
</div>
```</div>

**Comment by Tofandel** [comment]
Please provide your vue version and vue-quill version
