### ISSUE TITLE
readonly doesn't work with reactive elements

### ISSUE THREAD

**Issue by ata1704** [vueup/vue-quill#314]
**Version**
@vueup/vue-quill version 1.0.1

**Describe the bug**
readonly is not working properly with v-bind values.

**To Reproduce**
1. Starting with a Vue data property named isDisabled set to `true`
2. data property is bound to the QuillEditor via `:readOnly="isDisabled"`
3. Clicking on a button sets `isDisabled` to `false` (`@click="isDisabled = false"`)
4. Not able to edit the text in the Editor

**Expected behavior**
Editing the text should work with a bound data property as it does with a non reactive value.

**Reproduction link**
```
<template>
  <button v-if="isDisabled" @click="isDisabled = false" />

  <QuillEditor
    :toolbar="['bold', 'italic', 'underline']"
    theme="snow"
    v-model:content="content"
    :readOnly="isDisabled"
    contentType="html"
  >
  </QuillEditor>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { QuillEditor } from '@vueup/vue-quill';
import '@vueup/vue-quill/dist/vue-quill.snow.css';

export default defineComponent({
  props: {
    modelValue: { type: String, required: true },
  },
  emits: ['update:modelValue'],
  components: { QuillEditor },
  data() {
    return {
      isDisabled: true,
    };
  },
  computed: {
    content: {
      get() {
        return this.modelValue;
      },
      set(newValue: String) {
        this.$emit('update:modelValue', newValue);
      },
    },
  },
});
</script>
```

**Browser (please complete the following information):**
 - Browser Chrome
 - Version 109.0.5414.119

**Additional context**
I also tried to set is as a :options object. Doesn't work either.

**Comment by logikonline** [comment]
How is this stale?  It doesn;t work
