### ISSUE TITLE
Security issue with quill <=1.3.7

### ISSUE THREAD

**Issue by 1Map** [vueup/vue-quill#324]
https://github.com/vueup/vue-quill/blob/dc589e1f1a1d1f76e717abf7f031dc43dcfcadeb/packages/vue-quill/package.json#L45

A vulnerability in the HTML editor of Slab Quill allows an attacker to execute arbitrary JavaScript by storing an XSS payload (a crafted onloadstart attribute of an IMG element) in a text field. No patch exists and no further releases are planned.

This CVE is disputed. Researchers have claimed that this issue is not within the product itself, but is intended behavior in a web browser. More information can be found https://github.com/quilljs/quill/issues/3364.

**Comment by Tofandel** [comment]
This "CVE" doesn't show any way to reproduce it properly and the blog post explanation is basically that if you store html on the server and output it as is on the page you get XSS (`<div><image src=validateNonExistantImage.png onloadstart=alert(1337)> hey girl hey </div>`) 
Oh really 😱 😱 😱 

Quill does sanitize it properly and this "CVE" is not with quill but with all text editors that are stored server side to be displayed in html, they need to be properly sanitized before being output to an html page **_WITHOUT QUILL_**
