### ISSUE TITLE
bold cannot work.

### ISSUE THREAD

**Issue by leidexunuo** [vueup/vue-quill#326]
` <QuillEditor style="height:500px;" toolbar="essential" :placeholder="contentText" v-model:content="content" content-type="text" />`
<img width="722" alt="image" src="https://user-images.githubusercontent.com/12673432/219261073-53dfd83f-c397-4944-9331-c37b42aa3e0e.png">

this is my code, bold cannot work in browser.

**Comment by makerovski** [comment]
Hello ... Please provide more information, are you using Vue? Composition or options API ? What is the Method you are using, can you share or code, so we can analyze it better. Thank you!
