### ISSUE TITLE
How to use methods ?

### ISSUE THREAD

**Issue by igorraphael** [vueup/vue-quill#33]
How to use methods Vuequill, like setHTML,getHTML ...

I try use setHTML on ready event but return setHTML is not a function..

**Comment by luthfimasruri** [comment]
which version did you use?

**Comment by igorraphael** [comment]
1.0.0-beta-5

**Comment by luthfimasruri** [comment]
can you share the source code?

**Comment by igorraphael** [comment]
`
const quillReady = (quill) => {

     quill.setHTML('<h1>Hi</h1>');
     //quill.getEditor();
     //quill.setText('hi');
}

<QuillEditor onReady={(quill) => this.quillReady(quill)}  contetType='html' />
`

Well, i want to add html inside the editor, through a button and also through drag and drop. But only setText () works, and the others return : is not a function...

**Comment by luthfimasruri** [comment]
How to use methods in composition API:

``` vue
<template>
  <QuillEditor ref="myEditor" />
</template>

<script>
import { QuillEditor } from '@vueup/vue-quill'
import { ref, onMounted } from 'vue'
export default {
  components: {
    QuillEditor,
  },
  setup() {
    const myEditor= ref(null)
    onMounted(()=> {
      console.log(myEditor)
    })
  }
};
</script>
```

and sorry for the delayed reply.

**Comment by luthfimasruri** [comment]
Usage in option API:  
``` vue 
<template>
  <QuillEditor ref="myEditor" />
</template>

<script>
import { QuillEditor } from '@vueup/vue-quill'
export default {
  components: {
    QuillEditor,
  },
  mounted() {
    console.log(this.$refs.myEditor.getEditor())
  }
};
</script>
```
