### ISSUE TITLE
Theme does not dynamically update when theme prop value changes

### ISSUE THREAD

**Issue by cberthiaume** [vueup/vue-quill#341]
**Version**
@vueup/vue-quill version 1.1.1

**Describe the bug**
Changing the assigned theme via the `:theme` prop does not update the theme used by the editor.

**To Reproduce**
Create a component that contains a VueQuill editor. Assign the theme using `:theme="theme"` where `theme` is a `ref` with value 'snow'. Update `theme` to have the value 'bubble'.

**Expected behavior**
I expect the theme to change from 'snow' to 'bubble'.

**Reproduction link**
See [here](https://codesandbox.io/s/cranky-matsumoto-feyu3s?file=/src/components/HelloWorld.vue).

**Browser (please complete the following information):**
 - Firefox
 - 110.0.1

**Additional context**

**Comment by cberthiaume** [comment]
The same seems to be true for the `toolbar` prop. Is there some way to change the theme and toolbars after the component is created on the page? The demo on the [project page](https://vueup.github.io/vue-quill/) seems to do it so maybe I'm just doing it wrong.

Is it possible to see the demo code? I looked [here](https://github.com/vueup/vue-quill/tree/master/demo) but none of the demos there seem to match what is on the project page. I could be missing it.

Thanks!

**Comment by cberthiaume** [comment]
Beuller?

**Comment by itsyungtse** [comment]
@cberthiaume  Theme toggling in the demo [project page](https://vueup.github.io/vue-quill/) is not dynamic props. 
It reset the state of editor component, 
you can found in [source](https://github.com/vueup/vue-quill/blob/dcc9535f9eead1a0f071b4f320044b7f45a07623/docs/content/.vitepress/theme/components/demo/DemoEditor.vue), it calls the `myEditor.value.reinit()`.
So you could implement switching themes like this.

```javascript
watch([theme], () => {
  myEditor.value.reinit()
})
```
