### ISSUE TITLE
V-model:content is not working

### ISSUE THREAD

**Issue by atif0075** [vueup/vue-quill#342]
**Version**
"@vueup/vue-quill": "^1.1.1"

**Describe the bug**
it is not detecting v model value, i have to get the by custom function
```
let rawHtml = ref(null);
let getHTML = () => {
  rawHtml.value = document.querySelector(".ql-editor").innerHTML;
  console.log(rawHtml.value);
};
```

**To Reproduce**
```
import { ref } from "vue";
 import { QuillEditor } from "@vueup/vue-quill";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
const content = ref("Hello");
//template code
 <QuillEditor
      v-model:content="content"
      style="height: 456px"
      toolbar="essential"
      theme="snow"
    />

```
**Expected behavior**
It should take value from the content variable 

**Browser (please complete the following information):**
 - Browser chrome latest macos

**Comment by BombaraGianluca** [comment]
Hi, please fix this issue soon. 
I can't retrieve content changes. 
Thanks

**Comment by chenliangngng** [comment]
The same in 1.0.1

**Comment by colenocks** [comment]
@BombaraGianluca By default VueQuill uses 'delta' as it's content format [see docs](https://vueup.github.io/vue-quill/api/#contenttype). 
So you've gotta explicitly set the `content-type` to either `text` or in your case `html`

This should work (works for me)👇
```vue
import { ref } from "vue";
 import { QuillEditor } from "@vueup/vue-quill";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
const content = ref("Hello");
//template code
 <QuillEditor
      v-model:content="content"
      content-type="html"
      style="height: 456px"
      toolbar="essential"
      theme="snow"
    />
```

And if you decide to use the default content type -> `delta`. Then you have to create an instance of a Delta as a default value

```
import { QuillEditor, Delta } from "@vueup/vue-quill";
...
const content = ref(new Delta({ ops: [{ insert: '' }] }))
// or perhaps
const content = ref(new Delta({ ops: [] }))
```

**Comment by demiro** [comment]
it would help if this is in the DOCs.... since using v-model is the most common use case

**Comment by demiro** [comment]
Also, talking about DOCs, would it be possible to add an example on how to build a custom module and add it? (in composition / setup) ?

**Comment by kwbtdisk** [comment]
I've had same issue and my workaround, with fetching the right content from `this.$refs.myQuillEditor.getContents()`

```vue
<template>
  <QuillEditor
    ref="myQuillEditor"
    content-type="html"
    :content="modelValue"
    :options="editorOption"
    @textChange="() => onEditorChange()"
    @blur="() => onBlur()"
  />
</template>

<script>
import { QuillEditor } from '@vueup/vue-quill'
...
  methods: {
    onBlur(editor) {
      this.emitUpdate()
    },
    onEditorChange(delta) {
      this.emitUpdate()
    },
    emitUpdate() {
      this.$nextTick(() => {
        this.$emit('update:modelValue', this.$refs.myQuillEditor.getContents())
      })
    },
  },
...
```

**Comment by aeon3k** [comment]
thanks @colenocks 
for those who have had the following error : **"delta.slice is not a function"** , it's because the content of the editor should be initialized.
I did the following witht the composition api and inside a single file component

onMounted(() => {
  MyEditorContent.value = new Delta(props..whatever)
});
