### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by dannius** [vueup/vue-quill#39]
**Version**
@vueup/vue-quill version [e.g. 1.0.0-beta.6]

**Describe the bug**
interactive toolbar elements is not working. So i am trying with basic usage and seems like i can not change font size, first drop down is not working 

**To Reproduce**
i just tried to use  ```<quill-editor :theme="'snow'"></quill-editor>``` with default toolbar  and 'Normal' is not clickable in chrome. But demo works fine for me. In firefox everything ok
<img width="426" alt="Screen Shot 2021-06-06 at 2 02 50 PM" src="https://user-images.githubusercontent.com/38807114/120922115-fd971900-c6cf-11eb-9193-31d34c291fd2.png">

**Browser (please complete the following information):**
 - Browser chrome version 91.0.4472.77

Thanks!

**Comment by luthfimasruri** [comment]
Hmm, I'm not sure about this problem, because I tested it and it works:
[https://codesandbox.io/s/vue-quill-text-editor-forked-5jhod?file=/src/App.vue](https://codesandbox.io/s/vue-quill-text-editor-forked-5jhod?file=/src/App.vue)

**Comment by dannius** [comment]
@luthfimasruri seems like problem with browser, dont know exactly what happened but reinstall helps me. Thanks for sandbox!
