### ISSUE TITLE
Problem with focus()

### ISSUE THREAD

**Issue by igorraphael** [vueup/vue-quill#41]
**Version** 1.0.0-beta.5

**Describe the bug**
Following the documentantion:  "returns the Quill instance that backs the editor. While you can freely use this to access methods such as getText(), focus(), and much more." 

But focus() not work, getText, html is ok.

**To Reproduce**
1. Go use some method
2. get quill instance 
3. set focus
4. See warning in console and no focus

![vuequill](https://user-images.githubusercontent.com/38577695/121232422-f86cd200-c867-11eb-85d9-8b34b3798126.JPG)

**Comment by fylzero** [comment]
Still not working/fixed.  Bump/reopen.

**Comment by fylzero** [comment]
Resolved by https://github.com/vueup/vue-quill/pull/361

Update to v1.2.0 for focus method support
