### ISSUE TITLE
Cursor gets reset to beginning position after updating text

### ISSUE THREAD

**Issue by dfun90** [vueup/vue-quill#60]
**Version**
@vueup/vue-quill version 1.0.0-beta.7

**Describe the bug**
When typing even just one character into the editor and updating the v-model content using a wrapper the cursor jumps back to the beginning position at 0,0.

**To Reproduce**
The steps are described on the Codesandbox, but here again for clarity:
1. Click inside the editor to some text
2. Type a character
3. The cursor position gets now reset to the start at 0,0
Also the 'content' prop, which gets mapped to the v-model:content of the QuillEditor does not set the content of the Editor, I'd expect it to set it though.
You can use the DevTools (F12) and the 'Toggle Device Emulation' tool to see the mobile version, same bug occurs there as well.

**Expected behavior**
I expect the cursor to stay at the same position when content is changed and reached down to another component, etc.

**Reproduction link**
https://codesandbox.io/s/vue-quill-cursor-bug-2rwzu

**Browser (please complete the following information):**
- Microsoft Edge (Chromium, 91.0.864.71, 64bit, Windows 10)

**Additional context**
The linked Codesandbox shows the wrapper component I built which changes some visual things and options depending on if you are on a big screen (Desktop) or a small screen (Mobile). It uses `vue3-mq` for the screen size detection.   
In the `quillEditorSelectionChangeEvent` and `quillEditorUpdateContentEvent` methods in the `TextEditorWrapper.vue` I have some commented out code where I tried a workaround. Needless to say, that workaround didn't work out as expected, if you type too fast it breaks.

**Comment by nguyentrongbang** [comment]
I have the same problem :(

**Comment by fvena-portfolio** [comment]
I also have this problem

**Comment by mohammedmoutawakkil** [comment]
same problem ?!

**Comment by alexbonhomme** [comment]
I have the same issue... Unable to find a solution :-(

**Comment by hqy479992** [comment]
let quill  = this.$refs.quillEditor.getQuill()  //获取quillEditor实例
  let pos = quill.selection.savedRange.index //获取光标位置
  let insertStr = e.name   
        quill.insertEmbed(pos, insertStr); 
        quill.setSelection(pos + insertStr.length); //设置光标的位置 set   position
