### ISSUE TITLE
[Question] Try to use <div> instead <p> in content

### ISSUE THREAD

**Issue by Kanglinwu** [vueup/vue-quill#64]
**Version**
"@vueup/vue-quill": "^1.0.0-beta.7",

**Describe the bug**
When i use the v-model (value type: string) to bind the string on VueQuill component, default value ( by setHTML() method ) will be <p></p>, is it possible to use the <div> tag to replace it? i do the pre-search on google, i found only Quill document mention about this, but on vue-quill i can't find any solution

refer - https://github.com/quilljs/quill/issues/861

Kindly let me know if any idea for this, thanks : )

**Comment by TylerMRoderick** [comment]
@Kanglinwu this can be achieved the exact same way as in the issue you referred. Here is a vue 3 example:

```typescript
<script setup lang="ts">
import { Quill, QuillEditor } from '@vueup/vue-quill';

const Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);
</script>
```
