### ISSUE TITLE
css not loaded in after build

### ISSUE THREAD

**Issue by nishtman1366** [vueup/vue-quill#86]
Hi
I am using Laravel 8 + InertiaJs + Vue 3
everything works great in development but when I build the project the editor buttons are loaded like without css and nothing works at all in editor

These screenshots are from browser window

can anyone tell me what to do about this problem?

![Screenshot from 2021-09-18 13-10-19](https://user-images.githubusercontent.com/51849295/133882753-57e7b134-0279-41c2-ab94-f5f816f2c934.png)
![Screenshot from 2021-09-18 13-10-24](https://user-images.githubusercontent.com/51849295/133882755-027d9f20-4ba2-4af5-9cd9-edfe44a73b4d.png)
![Screenshot from 2021-09-18 13-10-27](https://user-images.githubusercontent.com/51849295/133882758-67ad22a7-4628-4ab1-a437-4efc05458e30.png)

**Comment by guptanishi** [comment]
@nishtman1366 did you get the solution for this issue?
